.PHONY: clean All

All:
	@echo "----------Building project:[ Runners - Debug ]----------"
	@cd "Runners" && "$(MAKE)" -f  "Runners.mk"
clean:
	@echo "----------Cleaning project:[ Runners - Debug ]----------"
	@cd "Runners" && "$(MAKE)" -f  "Runners.mk" clean
